// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FENGSHUIKOI.Data.Models;

public partial class Combo
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public int? ElementId { get; set; }

    public int? ProductDetailId { get; set; }

    public string ComboName { get; set; }

    public decimal ComboPrice { get; set; }

    public decimal? Discount { get; set; }

    public bool? Status { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Element Element { get; set; }

    public virtual Member Member { get; set; }

    public virtual ProductDetail ProductDetail { get; set; }
}