// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FENGSHUIKOI.Data.Models;

public partial class ProductDetail
{
    public int Id { get; set; }

    public string Description { get; set; }

    public int? ComboId { get; set; }

    public int? TypeId { get; set; }

    public string Color { get; set; }

    public string Name { get; set; }

    public int? Quantity { get; set; }

    public string Type { get; set; }

    public bool? Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public string Size { get; set; }

    public string Origin { get; set; }

    public virtual ICollection<Combo> Combos { get; set; } = new List<Combo>();

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    public virtual Type TypeNavigation { get; set; }
}