// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FENGSHUIKOI.Data.Models;

public partial class SuitableObject
{
    public int Id { get; set; }

    public int? ElementId { get; set; }

    public int? TypeId { get; set; }

    public string Color { get; set; }

    public string Size { get; set; }

    public string Direction { get; set; }

    public string Position { get; set; }

    public string Shape { get; set; }

    public string Volume { get; set; }

    public string WaterQuality { get; set; }

    public string WaterTemperature { get; set; }

    public string InformationDirection { get; set; }

    public string Flag { get; set; }

    public virtual Element Element { get; set; }

    public virtual Type Type { get; set; }
}