// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FENGSHUIKOI.Data.Models;

public partial class Member
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public bool? Status { get; set; }

    public string Avatar { get; set; }

    public string Phone { get; set; }

    public string StoreName { get; set; }

    public string X { get; set; }

    public string Y { get; set; }

    public string Address { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Combo> Combos { get; set; } = new List<Combo>();

    public virtual ICollection<MemberPackage> MemberPackages { get; set; } = new List<MemberPackage>();
}