// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FENGSHUIKOI.Data.Models;

public partial class Element
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime? TabooTime { get; set; }

    public string ImageUrl { get; set; }

    public bool? Status { get; set; }

    public string LuckyNumbers { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public string UpdateBy { get; set; }

    public virtual ICollection<Combo> Combos { get; set; } = new List<Combo>();

    public virtual ICollection<SuitableObject> SuitableObjects { get; set; } = new List<SuitableObject>();
}