// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FENGSHUIKOI.Data.Models;

public partial class MemberPackage
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public int? PackageId { get; set; }

    public DateTime? ExpiredDate { get; set; }

    public DateTime? BoughtAt { get; set; }

    public bool? Status { get; set; }

    public virtual Member Member { get; set; }

    public virtual Package Package { get; set; }
}